title: Lehmuskartanon Ratsastuskoulu
email: virtuaali@proton.me
description: >-
  Tervetuloa virtuaalitallillemme!
baseurl: "/lehmuskartanon-ratastuskoulu"
url: "https://tilli-simgame.github.io"

# Build settings
theme: minima # We will override this with our own layouts
plugins:
  - jekyll-feed
  - jekyll-seo-tag
