title: Vieraskirja Demo
email: virtuaali@proton.me
description: >-
  Tämä on Vieraskirja Demo.
baseurl: "/vieraskirja-demo"
url: "https://tilli-simgame.github.io"

# Build settings
theme: minima # We will override this with our own layouts
plugins:
  - jekyll-feed
  - jekyll-seo-tag
